CFLAGS = -g -Wall

LIBS = -l stdc++ -lm

CXX = g++

planets: planets.o calcR.h force.h pos.h vel.h tim.h
	$(CXX) $(CFLAGS) $(LIBS) planets.o calcR.h force.h pos.h vel.h tim.h -o planets

%.o: %.cc
	$(CXX) $(CFLAGS)	$< -c -o $@
	
%: %.cc Makefile
	$(CXX) $(CFLAGS) $(LIBS) $< -o $@